### ISSUE TITLE
shrink_to_fit not defined

### ISSUE THREAD

**Issue by xebecnan** [TeamHypersomnia/rectpack2D#1]
https://github.com/TeamHypersomnia/rectpack2D/blob/master/src/pack.cpp#L254

pack.cpp:254:12: error: 'class std::vector<rect_xywhf*>' has no member named 'shrink_to_fit'

**Comment by geneotech** [comment]
This is actually a silly attempt at "optimization" that is not at all needed. I've removed the call.
