### ISSUE TITLE
remove the pathological multiplier for being useless

### ISSUE THREAD

**Issue by 1e1001** [TeamHypersomnia/rectpack2D#10]
the pathological multiplier is defined as
```
max(w, h) / min(w, h) × w × h
```
substituting for all possible orderings of `w` and `h`:
- `w < h`: `h / w × w × h` = `h × h`
- `w > h`: `w / h × w × h` = `w × w`
- `w = h`: `n / n × n × n` = `n × n` (where `n` = `w` = `h`)

thus this is equvialent to `max(w, h)²`

because the comparator is only used for sorting the rectangles, and negative-sized rectangles are generally not used, `max(w, h)` and `max(w, h)²` will sort the rectangles in the same order

since `max(x, y)` is already one of the comparators, this means that the pathological ordering is redundant

**Comment by geneotech** [comment]
Sorry for such an extremely late reply, only now wrapped my head around this :) This is indeed the case, tested it on a larger dataset to be sure. Thank you for your keen observation!
