### ISSUE TITLE
Regression in results from old rectpack2D

### ISSUE THREAD

**Issue by NiklasRosenstein** [TeamHypersomnia/rectpack2D#5]
Hi, I am comparing the results of the old and current rectpack2D version. It appears the old version performs better in terms of the packing.

Results from the old version (33 rectangles packed):

![pack_pack_old](https://user-images.githubusercontent.com/1318438/42700133-2114073a-86c3-11e8-83ae-dc302fea565e.jpg)

Results from the current version (`find_best_packing()`, 12 rectangles packed):

![pack_pack_new_sorted](https://user-images.githubusercontent.com/1318438/42700309-a5549fe6-86c3-11e8-88c3-ddc254a9415c.jpg)

Results from the current version (`find_best_packing_dont_sort()`, 22 rectangles packed):

![pack_pack_new_unsorted](https://user-images.githubusercontent.com/1318438/42700233-6397cc54-86c3-11e8-97a5-6fc85690b253.jpg)

This is the code I use in the new version:

```cpp
    using spaces_type = rectpack2D::empty_spaces<true, rectpack2D::default_empty_spaces>;
    using rect_type = spaces_type::output_rect_type;
    std::vector<rect_type> rectangles;
    std::vector<bool> acceptedRects;
    int numAcceptedRects = 0;
    for (auto& img : sourceImages) {
      rectangles.emplace_back(rectpack2D::rect_xywh(0, 0, ofx::width(img->bounds()) + xMargin, ofx::height(img->bounds()) + yMargin));
      acceptedRects.push_back(false);
    }
    int maxSize = std::max(width, height) - std::max(xMargin, yMargin);
    auto reportUnsuccessful = [&](rect_type& rect) { return false; };
    auto reportSuccessful = [&](rect_type& rect) {
      int index = (&rect - rectangles.data());
      acceptedRects[index] = true;
      numAcceptedRects++;
      return !effect.abort();
    };
    std::cout << "sourceImages.size(): " << sourceImages.size() << "\n";
    std::cout << "rectangles.size(): " << rectangles.size() << "\n";
    std::cout << "discardStep: " << discardStep << "\n";
    std::cout << "maxSize: " << maxSize << "\n";
    rectpack2D::rect_wh const resultSize = rectpack2D::find_best_packing<spaces_type>(
      rectangles,
      rectpack2D::make_finder_input(
        maxSize,
        discardStep,
        reportSuccessful,
        reportUnsuccessful
      )
    );
```

Any idea where that regression comes from? Is it due to how I use the new version?

**Comment by NiklasRosenstein** [comment]
PS: The discardStep doesn't seem to have any effect on the results in either version.

**Comment by geneotech** [comment]
Hey, I'll look into this immediately. I'll compare results to the atlas currently generated for my game.

**Comment by NiklasRosenstein** [comment]
Hey @geneotech thanks for the quick reply.

Actually, like the minute I posted this, I recognized that maybe `reportUnsuccessfuly` shouldn't return `false`, so that it can still try to pack other rectangles. 😅 

The result is very similar to the old version now and packs 33 rectangles again!

![pack_pack_new_sorted_noabort](https://user-images.githubusercontent.com/1318438/42700716-ddeadd7e-86c4-11e8-8d76-0c34d92d8348.jpg)

I was following the `example/main.cpp` source here

https://github.com/TeamHypersomnia/rectpack2D/blob/5ff6badc360ee2deec3b48dc72480081dffb7c7a/example/main.cpp#L45-L48

**Comment by geneotech** [comment]
Oh, I see! Now it makes sense! My heart has skipped a beat for a while there, hahah :joy:  

Still, what bugs me that the algorithm has aborted if you've provided a suitable max_size in the first place.
Are you sure that the  ``!effect.abort();`` call doesn't return false for some successful insertions?

**Comment by geneotech** [comment]
I should also probably return some suitably named enumeration type - e.g. ``callback_result::ABORT`` - instead of true/false, as this will remove the confusion.

**Comment by geneotech** [comment]
Or is it the case that you've passed more than just 33 rectangles and you just wanted the algorithm to fit as many of the input rectangles as possible? This is, of course, a correct use case as well, and here you'd have to return true for the unsuccessful insertion for the algorithm to continue.

**Comment by geneotech** [comment]
I'm also wondering what might be the reason behind this inefficient packing. Some rectangles could still be inserted into the right-bottom corner. The latest of my atlases packs pretty tightly:

![atl](https://user-images.githubusercontent.com/3588717/42701782-c84980e4-86c7-11e8-8e74-9b972e2f2a9d.png)

Can you try increasing the max_size so that *all* input rectangles are sure to fit successfully?

**Comment by NiklasRosenstein** [comment]
> Still, what bugs me that the algorithm has aborted if you've provided a suitable max_size in the first place.
Are you sure that the !effect.abort(); call doesn't return false for some successful insertions?

The `abort()` call would only return false if the OFX Host wants to abort the rendering process, and I wouldn't get any output after that. :)

> Or is it the case that you've passed more than just 33 rectangles and you just wanted the algorithm to fit as many of the input rectangles as possible? This is, of course, a correct use case as well, and here you'd have to return true for the unsuccessful insertion for the algorithm to continue.

Indeed, I am trying to pack as many into a fixed size texture (8k) as possible. 

> I'm also wondering what might be the reason behind this inefficient packing. Some rectangles could still be inserted into the right-bottom corner.

Actually there is only one remaining rectangle of size  (4037, 477) which won't fit into the bottom left corner (too wide).  
What *does* confuse me is that it isn't packed "earlier" in the process, as the `find_best_packing()` (ie. with sorting) should pack bigger rectangles first, no?

> Can you try increasing the max_size so that all input rectangles are sure to fit successfully?

It can pack all of them into a (8247, 7946) rectangle (result size) when choosing max_size = 8313.

**Comment by geneotech** [comment]
This is strange indeed.

Is there a possibility that you could send me all the input images so that I can play with this dataset?

**Comment by geneotech** [comment]
The simplest way that I see to enable and disable flipping at runtime, is to compile the code with ``allow_flip = true``, use ``rect_xywhf`` everywhere and just add a boolean to the ``empty_spaces`` class called "enable_flipping" - if this is false, it would just never try to flip the input rectangles from within the ``insert`` function, always leaving the ``rect_xywhf::flipped`` value at false.

**Comment by geneotech** [comment]
Unless you want to avoid duplicating most of the code with templates, but effectively want to use both ``rect_xywh`` *and* ``rect_xywhf`` - then it might prove quite hard, and a lot of functions would get compiled for both types anyway.

**Comment by NiklasRosenstein** [comment]
> Is there a possibility that you could send me all the input images so that I can play with this dataset?

Yes, here they are:  [rectangles.zip](https://github.com/TeamHypersomnia/rectpack2D/files/2193546/rectangles.zip)

> The simplest way that I see to enable and disable flipping at runtime, is to [...]

Thanks for the tips -- As far as I can see that would require me to edit the rectpack2D source.. (?)  
I chose to go with this method, it requires a copy of the rectangles but for the number of rectangles that I need to pack, that is rather negligible!

```cpp
struct TexRect : rectpack2D::rect_xywhf {
  using rectpack2D::rect_xywhf::rect_xywhf;
  bool accepted = false;
  TexRect(rectpack2D::rect_xywh const& r) : TexRect(r.x, r.y, r.w, r.h, false) {}
  TexRect(rectpack2D::rect_xywhf const& r) : TexRect(r.x, r.y, r.w, r.h, r.flipped) {}
  operator rectpack2D::rect_xywh () const { return {x, y, w, h}; }
};


template <bool allow_flip>
rectpack2D::rect_wh findBestPacking(int max_size, int discard_step, std::vector<TexRect>& rectangles) {
    using spaces_type = rectpack2D::empty_spaces<allow_flip, rectpack2D::default_empty_spaces>;
    using rect_type = spaces_type::output_rect_type;

    std::vector<rect_type> compute_rects(rectangles.size());
    for (int i = 0; i < rectangles.size(); ++i) {
      compute_rects[i] = rectangles[i];
    }

    return rectpack2D::find_best_packing<spaces_type>(
      compute_rects,
      rectpack2D::make_finder_input(
        max_size,
        discard_step,
        [&](rect_type& rect) {  // successful
          int index = (&rect - compute_rects.data());
          rectangles[index] = TexRect(rect);
          rectangles[index].accepted = true;
          return true;  // TODO: effect.abort()
        },
        [&](rect_type& rect) { return true; }  // unsuccessful
      )
    );
}
```

**Comment by geneotech** [comment]
@NiklasRosenstein Now just pass ``flipping_option::ENABLED`` or ``flipping_option::DISABLED`` as the last argument to ``make_finder_input``.

**Comment by geneotech** [comment]
Provided a max_size of ``16384``, I am getting this packing:

![atl](https://user-images.githubusercontent.com/3588717/42706054-ccdc4d90-86d5-11e8-9e37-7f15c6f6d94d.jpg)

It is sized ``7788x8471``, so it exceeds your max size (8k) by just a little. We were unfortunate enough to fall at a boundary of what the algorithm can do, so it might have chosen a rectangle order where the biggest rectangle wasn't the first to one go - it's possible, e.g. a pathological multiplier (``float(max_side()) / min_side() * area()``) isn't proportional just to size, but also how "deformed" the rectangle is.

You could try using the finder's overload where you can specify your own ordering predicates, and don't pass the pathological predicate.

Or just try passing a max size of ``8471``? Though this probably exceeds your maximum texture size already.

**Comment by geneotech** [comment]
Padded, it looks like this (``7794x8476``):

![leaves_padded](https://user-images.githubusercontent.com/3588717/42706579-9888826e-86d7-11e8-8400-1e2524c8d2b0.jpg)

Can I add it to ``README.md`` as an example packing? Such a cute collection.

**Comment by geneotech** [comment]
Interestingly, despite ``7794x8476`` being less pixels in total than ``8192x8192``, the new algorithm must have been unable to pack the rectangles into a square of side = 8192, just like the old algorithm was able to. This might have been pure luck, as even if both versions were given the same rectangles orderings, the order of considered empty spaces would be a little different in both due to their completely different implementations. 

The dataset is also quite hard as there aren't many little filler rectangles to fit the remaining empty spaces.

**Comment by geneotech** [comment]
I've improved the efficiency by starting the packing attempt always from the initially passed maximum bin side, instead of starting from a possibly rectangular bin determined by an order that has performed best: ``8244x7490`` (this is less pixels than all results in this thread):

![atlless](https://user-images.githubusercontent.com/3588717/42707552-d8b1c65e-86da-11e8-9412-54c580bd2696.jpg)

Indeed, even my game atlas packs better:

![atlno](https://user-images.githubusercontent.com/3588717/42707674-5501d348-86db-11e8-8533-5b1e11e34f73.png)

**Comment by NiklasRosenstein** [comment]
Happy to see you are having fun with this dataset :-) Sure, you can go ahead and add the result to your README file!

I will be unable to make any further tests before monday, sorry about that. But thanks a lot for making it pack even better!

**Comment by geneotech** [comment]
I remember passing ``16384`` (2^14) as the maximum size, perhaps the algorithm was trying more fortunate sizes then.

Each comparator invokes another packing attempt with the rectangle order that it produces. If you pass a lambda that compares area, the algorithm will try inserting the rectangles beginning from the one that has the biggest area, etc. There are other sensible methods to compare rectangles, like the maximum of their sides. Usually, if "bigger" rectangles go earlier, the packing turns out better, however I can offer no proof of that claim :grinning: 

Thus if you add twice as many comparators, the algorithm will run twice as long.

Additionally, perhaps you could modify ``best_packing_for_ordering_impl`` so that it checks each possible bin size, pixel by pixel, instead of performing a binary search.

**Comment by NiklasRosenstein** [comment]
Hey @geneotech 

After properly cropping all leaves, it can actually pack all 41 rectangles! No need for the other packing comparators :)

This is pretty darn awesome. Thanks for your hard work on this library 😃 

Here's the better cropped version of the leafs:  [leafs.zip](https://github.com/TeamHypersomnia/rectpack2D/files/2232545/leafs.zip)

**Comment by geneotech** [comment]
Hey hey @NiklasRosenstein! Glad you've got it properly working! May you possibly share the results? :blush:

**Comment by NiklasRosenstein** [comment]
Of course! Unfortunately the 8k resolution as PNG is too much for GitHub (max 10MB per file) so here's just a 2K version

![leaves_diffuse](https://user-images.githubusercontent.com/1318438/43272773-1af3fed6-90fb-11e8-9f64-91bed9105922.png)

![leaves_normal](https://user-images.githubusercontent.com/1318438/43272774-1b19a708-90fb-11e8-835a-fa9c2fc63989.png)
