### ISSUE TITLE
Area may overflow when the rectangle is too large

### ISSUE THREAD

**Issue by zxhcho** [TeamHypersomnia/rectpack2D#7]
Hi Patryk!
    I used your lib for scientific research about texture packing recently. 
    We know the texture coordinates of a mesh was recorded by float type ( [0,1] at mots time). If I want to use your API,  at first I must use std::floor and std::ceil to find an int-type bounding box for each rectangle; in order to lower the round-off errors in the process, I choose to enlarge the origin texture by a factor. Then I found your code behave poorly, after some examination, I found the area and other info used in your sort function is int type, if I choose a large factor, like 2048 where the edge length is very large, your area calculation may overflow to a negative number, which makes your sort function behave in a wrong way.
   I advise you to add a template to determine your rect_xywh member type, or I give you a pull request later.

Best wishes.

**Comment by geneotech** [comment]
@zxhcho 
Hello! Thanks a lot for reaching out! It absolutely makes sense to templatize this struct, it's just that `int` was enough for my particular usecase. I am loaded with work currently so I'll be grateful a ton if you submit a pull request. 

Cheers!

**Comment by geneotech** [comment]
Also do let me know about the details of your research, I'm always curious where this stuff is being used! ☺️

**Comment by zxhcho** [comment]
> @zxhcho
> Hello! Thanks a lot for reaching out! It absolutely makes sense to templatize this struct, it's just that `int` was enough for my particular usecase. I am loaded with work currently so I'll be grateful a ton if you submit a pull request.
> 
> Cheers!

OK. I'm glad to offer you a pull request later. Thanks for your code again.

**Comment by zxhcho** [comment]
> Also do let me know about the details of your research, I'm always curious where is this stuff being used!

It's very similar to your application, I'll give you a new issue to talk about this top later.

**Comment by zxhcho** [comment]
Our application is very similar to yours.

As we know, when rendering a 3D object, its surface was mapped into a 2D Parameter domain. Then we can give attributes to each point like color, displacement,  normal, and so on.

In this mapping process, we need to keep the shape(each face before and after mapping) with low distortions. But according to differential geometry theory, In order to get a 2D parameterization with low distortion, cutting of surface is unavoidable. That's to say, we usually cut the surface into many pieces and parameterize them separately.

In our research, we'll use your method to pack these pieces into one big parameter domain as a post-process step.

Your method really saves a lot of time for showing our research result. We are glad to tell you once our paper is accepted(maybe in one year).
